### ISSUE TITLE
Changing the `ssl_certificate_id` for an existing load balancer fails

### ISSUE THREAD

**Issue by redterror** [chef-boneyard/chef-provisioning-aws#393]
I built an ELB with a self signed cert, then when I tried to change the cert with a real one I got this error / stack trace:

```
AWS::Core::OptionGrammar::FormatError: expected string value for option ssl_certificate_id
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/option_grammar.rb:93:in `validate'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/option_grammar.rb:590:in `block in validate'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/option_grammar.rb:586:in `each'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/option_grammar.rb:586:in `validate'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/option_grammar.rb:601:in `request_params'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/query_request_builder.rb:37:in `populate_request'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:740:in `block (2 levels) in define_client_method'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:560:in `build_request'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:491:in `block (3 levels) in client_request'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/response.rb:175:in `call'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/response.rb:175:in `build_request'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/response.rb:114:in `initialize'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:203:in `new'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:203:in `new_response'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:490:in `block (2 levels) in client_request'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:391:in `log_client_request'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:477:in `block in client_request'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:373:in `return_or_raise'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/client.rb:476:in `client_request'
(eval):3:in `set_load_balancer_listener_ssl_certificate'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/elb/listener.rb:79:in `server_certificate='
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/bundler/gems/chef-provisioning-aws-e1b223484fef/lib/chef/provisioning/aws_driver/driver.rb:340:in `block (2 levels) in allocate_load_balancer'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/mixin/why_run.rb:52:in `call'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/mixin/why_run.rb:52:in `add_action'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/provider.rb:175:in `converge_by'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-provisioning-1.5.0/lib/chef/provisioning/chef_provider_action_handler.rb:54:in `perform_action'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/bundler/gems/chef-provisioning-aws-e1b223484fef/lib/chef/provisioning/aws_driver/driver.rb:204:in `block in allocate_load_balancer'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/bundler/gems/chef-provisioning-aws-e1b223484fef/lib/chef/provisioning/aws_driver/driver.rb:339:in `call'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/bundler/gems/chef-provisioning-aws-e1b223484fef/lib/chef/provisioning/aws_driver/driver.rb:339:in `block in allocate_load_balancer'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/collection.rb:48:in `each'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/collection.rb:48:in `block in each'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/collection/simple.rb:74:in `_each_batch'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/collection.rb:80:in `each_batch'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/aws-sdk-v1-1.66.0/lib/aws/core/collection.rb:47:in `each'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/bundler/gems/chef-provisioning-aws-e1b223484fef/lib/chef/provisioning/aws_driver/driver.rb:315:in `allocate_load_balancer'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-provisioning-1.5.0/lib/chef/provider/load_balancer.rb:35:in `block in <class:LoadBalancer>'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/provider/lwrp_base.rb:86:in `instance_eval'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/provider/lwrp_base.rb:86:in `block in action'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/provider.rb:144:in `run_action'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/resource.rb:585:in `run_action'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/runner.rb:49:in `run_action'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block (2 levels) in converge'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/runner.rb:81:in `each'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/runner.rb:81:in `block in converge'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:83:in `block in execute_each_resource'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:116:in `call_iterator_block'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:104:in `iterate'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/resource_collection/resource_list.rb:81:in `execute_each_resource'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/runner.rb:80:in `converge'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/client.rb:653:in `block in converge'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/client.rb:648:in `catch'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/client.rb:648:in `converge'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/client.rb:687:in `converge_and_save'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/client.rb:269:in `run'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/application.rb:270:in `block in fork_chef_client'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/application.rb:258:in `fork_chef_client'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/application.rb:224:in `block in run_chef_client'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/application.rb:212:in `run_chef_client'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/application/client.rb:408:in `block in interval_run_chef_client'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/application/client.rb:398:in `loop'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/application/client.rb:398:in `interval_run_chef_client'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/application/client.rb:388:in `run_application'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/lib/chef/application.rb:60:in `run'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/gems/chef-12.5.1/bin/chef-client:26:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/bin/chef-client:23:in `load'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/bin/chef-client:23:in `<main>'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.1@chef-repo/bin/ruby_executable_hooks:15:in `<main>'
```

My recipe follows exactly the [load_balancer.rb example](https://github.com/chef/chef-provisioning-aws/blob/master/docs/examples/load_balancer.rb#L35).

Manually changing the certificate in the AWS console resulted in a successful chef run.

**Comment by keen99** [comment]
:+1: 

Just ran into this after applying the wrong cert to a dozen ELBs and trying to update it.

    [2016-02-02T18:22:53-05:00] ERROR: expected string value for option ssl_certificate_id

where of course it does converge to a string:

     load_balancer_options {:listeners=>[{:port=>80, :protocol=>:http, :instance_port=>8080, :instance_protocol=>:http}, {:port=>443, :protocol=>:https, :instance_port=>8080, :instance_protocol=>:http, :ssl_certificate_id=>"arn:aws:iam::123456789900:server-certificate/star.example.com_example.com_Dec__9_15.53.38_2015_GMT_to_Dec__9_15.53.38_2017_GMT"}], :subnets=>["centraltech-us-west-2a", "centraltech-us-west-2b", "centraltech-us-west-2c"], :security_groups=>["sg-123456"]}


Guess I'll be patching this tonight. :/

**Comment by keen99** [comment]
Well....yeah,  Nil is not a string.

https://github.com/chef/chef-provisioning-aws/blob/f51b06c/lib/chef/provisioning/aws_driver/driver.rb#L342

```
                perform_action.call("    update server certificate from #{listener.server_certificate} to #{desired_listener[:server_certificate]}") do
                  listener.server_certificate = desired_listener[:server_certificate]
```

```


# DSR: desired_listener[:server_certificate]
# DSR: type desired_listener[:server_certificate] NilClass
# DSR: dump desired_listener {:port=>443, :protocol=>:https, :instance_port=>8080, :instance_protocol=>:http, :ssl_certificate_id=>"arn:aws:iam::123:server-certificate/star.xyz_xyz_Dec__9_15.53.38_2015_GMT_to_Dec__9_15.53.38_2017_GMT"}
```

**Comment by cgunasree08** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
