### ISSUE TITLE
call to aws_eip_address failing with NoMethodError: undefined method `[]' for nil:NilClass

### ISSUE THREAD

**Issue by ff-agrawal** [chef-boneyard/chef-provisioning-aws#579]
## Description
I am running provisioning to create machine and then assigning public ip to it

## Gem Version
chef-provisioning-aws-3.0.7
chef-provisioning-2.7.4

## Platform Version
Linux
Linux ip-10-123-0-160 4.9.70-25.242.amzn1.x86_64 #1 SMP Wed Jan 3 05:36:22 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Tell us which Operating System distribution and version you are running.

## Replication Case
    aws_eip_address 'bastion-elastic-ip' do
      associate_to_vpc true
      machine ec2_name
    end

`Generated at 2019-03-22 14:13:11 +0530
NoMethodError: undefined method `[]' for nil:NilClass
/Users/ankitagrawal1/.chefdk/gem/ruby/2.5.0/gems/chef-provisioning-aws-3.0.7/lib/chef/provisioning/aws_driver/driver.rb:114:in `initialize'
/Users/ankitagrawal1/.chefdk/gem/ruby/2.5.0/gems/chef-provisioning-aws-3.0.7/lib/chef/provisioning/aws_driver/driver.rb:102:in `new'
/Users/ankitagrawal1/.chefdk/gem/ruby/2.5.0/gems/chef-provisioning-aws-3.0.7/lib/chef/provisioning/aws_driver/driver.rb:102:in `from_url'
/Users/ankitagrawal1/.chefdk/gem/ruby/2.5.0/gems/chef-provisioning-2.7.4/lib/chef/provisioning.rb:86:in `driver_for_url'
/Users/ankitagrawal1/.chefdk/gem/ruby/2.5.0/gems/chef-provisioning-2.7.4/lib/chef/provisioning/chef_run_data.rb:105:in `driver_for_url'
/Users/ankitagrawal1/.chefdk/gem/ruby/2.5.0/gems/chef-provisioning-2.7.4/lib/chef/provisioning/chef_run_data.rb:84:in `driver_for'
/Users/ankitagrawal1/.chefdk/gem/ruby/2.5.0/gems/chef-provisioning-aws-3.0.7/lib/chef/provisioning/aws_driver/aws_resource_with_entry.rb:47:in `get_id_from_managed_entry'
/Users/ankitagrawal1/.chefdk/gem/ruby/2.5.0/gems/chef-provisioning-aws-3.0.7/lib/chef/provisioning/aws_driver/aws_resource_with_entry.rb:81:in `get_driver_and_id'
/Users/ankitagrawal1/.chefdk/gem/ruby/2.5.0/gems/chef-provisioning-aws-3.0.7/lib/chef/provisioning/aws_driver/aws_resource_with_entry.rb:56:in `to_s'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/formatters/doc.rb:288:in `resource_action_start'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/event_dispatch/dispatcher.rb:43:in `call'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/event_dispatch/dispatcher.rb:43:in `block in call_subscribers'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/event_dispatch/dispatcher.rb:34:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/event_dispatch/dispatcher.rb:34:in `call_subscribers'
(eval):2:in `resource_action_start'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/resource.rb:556:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/runner.rb:70:in `run_action'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/runner.rb:98:in `block (2 levels) in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/runner.rb:98:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/runner.rb:98:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/resource_collection/resource_list.rb:94:in `block in execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/resource_collection/stepable_iterator.rb:114:in `call_iterator_block'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/resource_collection/stepable_iterator.rb:85:in `step'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/resource_collection/stepable_iterator.rb:103:in `iterate'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/resource_collection/stepable_iterator.rb:55:in `each_with_index'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/resource_collection/resource_list.rb:92:in `execute_each_resource'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/runner.rb:97:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/client.rb:720:in `block in converge'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/client.rb:715:in `catch'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/client.rb:715:in `converge'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/client.rb:754:in `converge_and_save'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/client.rb:286:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:279:in `block in run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:261:in `run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application/client.rb:444:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/lib/chef/application.rb:66:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.5.0/gems/chef-14.10.9/bin/chef-client:25:in `<top (required)>'
/usr/local/bin/chef-client:295:in `load'
/usr/local/bin/chef-client:295:in `<main>'`

**Comment by ff-agrawal** [comment]
@jjlimepoint , @mattyait I see that you guys recently committed wondering if you can help check the issue or point me to correct person.

**Comment by cgunasree08** [comment]
This issue or pull request is being automatically closed because the repository is being archived as part of the [Repository Standardization Initiative](https://github.com/chef-boneyard/oss-repo-standardization-2025).
